<template>
    <FormDashboard
        :createUrl="API_ENDPOINT.CHAT_CREATE"
        :name="PAGE_NAME.DASHBOARD_CHAT"
        :readUrl="API_ENDPOINT.CHAT_READ"
        :schema="createChatSchema"
        title="Chat"
        :updateUrl="API_ENDPOINT.CHAT_UPDATE"
    >
        <FieldText
            label="Nombre"
            name="name"
        />
    </FormDashboard>
</template>
