<template>
    <FormDashboard
        :createUrl="API_ENDPOINT.CHAT_AGENT_CREATE"
        :name="PAGE_NAME.DASHBOARD_CHAT_AGENT"
        :readUrl="API_ENDPOINT.CHAT_AGENT_READ"
        :schema="chatAgentSchema"
        title="Agente"
        :updateUrl="API_ENDPOINT.CHAT_AGENT_UPDATE"
    >
        <FieldText
            label="Nombre"
            name="name"
        />
        <FieldTextarea
            label="Descripción"
            name="description"
        />
        <FieldModelText
            label="Model"
            name="model"
        />
        <FieldTextarea
            label="Instrucción"
            name="instruction"
        />
    </FormDashboard>
</template>
