<template>
    <FormDashboard
        name="dashboard-model"
        :schema="modelSchema"
        title="Modelo"
        url="/api/model"
    >
        <FieldText
            label="Nombre"
            name="name"
        />
        <FieldModelText
            label="Model"
            name="value"
        />
        <FieldRole
            label="Roles"
            multiple
            name="roles"
        />
    </FormDashboard>
</template>
