<template>
    <FormDashboard
        :createUrl="API_ENDPOINT.MODEL_CREATE"
        :name="PAGE_NAME.DASHBOARD_MODEL"
        :readUrl="API_ENDPOINT.MODEL_READ"
        :schema="modelSchema"
        title="Modelo"
        :updateUrl="API_ENDPOINT.MODEL_UPDATE"
    >
        <FieldText
            label="Nombre"
            name="name"
        />
        <FieldModelText
            label="Modelo"
            name="value"
        />
        <FieldRole
            label="Roles"
            multiple
            name="roles"
        />
    </FormDashboard>
</template>
