<template>
    <FormDashboard
        name="dashboard-chat-agent"
        :schema="chatAgentSchema"
        title="Agente"
        url="/api/chat-agent"
    >
        <FieldText
            label="Nombre"
            name="name"
        />
        <FieldTextarea
            label="Descripción"
            name="description"
        />
        <FieldModelText
            label="Model"
            name="model"
        />
        <FieldEditor
            label="Instrucción"
            name="instruction"
        />
    </FormDashboard>
</template>
