<template>
    <FormDashboard
        :createUrl="API_ENDPOINT.PROMPT_CREATE"
        :name="PAGE_NAME.DASHBOARD_PROMPT"
        :readUrl="API_ENDPOINT.PROMPT_READ"
        :schema="promptSchema"
        title="Prompt"
        :updateUrl="API_ENDPOINT.PROMPT_UPDATE"
    >
        <FieldText
            label="Descripción"
            name="description"
        />
        <FieldText
            label="Clave"
            name="key"
        />
        <FieldTextarea
            label="Valor"
            name="value"
        />
    </FormDashboard>
</template>
