<template>
    <FormDashboard
        name="dashboard-user"
        :schema="userSchema"
        title="Usuario"
        url="/api/user"
    >
        <FieldText
            label="Nombre"
            name="name"
        />
        <FieldText
            label="Apellido"
            name="surname"
        />
        <FieldText
            label="Correo electrónico"
            name="email"
        />
        <FieldRole
            label="Rol"
            name="role"
        />
    </FormDashboard>
</template>
