<template>
    <FormDashboard
        name="dashboard-prompt"
        :schema="promptSchema"
        title="Prompt"
        url="/api/prompt"
    >
        <FieldText
            label="Descripción"
            name="description"
        />
        <FieldText
            label="Clave"
            name="key"
        />
        <FieldTextarea
            label="Valor"
            name="value"
        />
    </FormDashboard>
</template>
