<template>
    <FormDashboard
        :createUrl="API_ENDPOINT.USER_CREATE"
        :name="PAGE_NAME.DASHBOARD_USER"
        :readUrl="API_ENDPOINT.USER_READ"
        :schema="userSchema"
        title="Usuario"
        :updateUrl="API_ENDPOINT.USER_UPDATE"
    >
        <FieldText
            label="Nombre"
            name="name"
        />
        <FieldText
            label="Apellido"
            name="surname"
        />
        <FieldText
            label="Correo electrónico"
            name="email"
        />
        <FieldRole
            label="Rol"
            name="role"
        />
    </FormDashboard>
</template>
